included: # paths to include during linting. `--path` is ignored if present.
  - Sources
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Tests

large_tuple:
  - 3
  - 4
identifier_name:
  min_length: # only min_length
    error: 3 # only error
  excluded: # excluded via string array
    - id
    - URL
    - GlobalAPIKey
    - i
    - j
    - k
    - h
    - x
    - y
    - z
reporter: "xcode"

